// models/models.go
package models

import (
	//"database/sql"
	"database/sql"
	"fmt"
	"log"
	"os"
	"time"

	_ "github.com/go-sql-driver/mysql" // MySQL driver for database/sql
)

var db *sql.DB

const dateFormat = "2006-01-02"

func ConnectDB() error {

	// --- 2. Read parameters and interpolate DSN ---
	dbUser := os.Getenv("DB_USER")
	dbPassword := os.Getenv("DB_PASSWORD")
	dbHost := os.Getenv("DB_HOST")
	dbPort := os.Getenv("DB_PORT")
	dbName := os.Getenv("DB_NAME")

	/* データベース接続設定 */
	connStr := "%s:%s@tcp(%s:%s)/%s"
	var localErr error
	db, localErr = sql.Open("mysql", fmt.Sprintf(connStr, dbUser, dbPassword, dbHost, dbPort, dbName))
	if localErr != nil {
		return localErr
	}

	/* 接続確認（オプション） */
	if localErr = db.Ping(); localErr != nil {
		db.Close()
		return localErr
	}

	log.Println("Successfully connected to the database!")
	return nil
}

func InsertOrUpdateSalesRecord(input *DailyReportRaw) (record interface{}, found bool, mode string, err error) {
	if input == nil {
		return nil, false, "", fmt.Errorf("input cannot be nil")
	}

	parsedDate, err := time.Parse(dateFormat, input.DateString)
	if err != nil {
		return nil, false, "", fmt.Errorf("invalid date format: %v", err)
	}

	// Check if the record exists
	var existingID int
	query := `SELECT id FROM 日次報告ﾃｰﾌﾞﾙ WHERE id = ?`
	err = db.QueryRow(query, input.ID).Scan(&existingID)

	if err != nil && err != sql.ErrNoRows {
		// Return if there's an error other than no rows found
		return nil, false, "", fmt.Errorf("error checking for existing record: %v", err)
	}

	if err == nil {
		// Record exists, perform an update
		fmt.Println("Record exists, performing update...")
		updateQuery := `
            UPDATE 日次報告ﾃｰﾌﾞﾙ T1
            SET T1.ID = ?,
T1.日付 = ?,
T1.天気ｺｰﾄﾞ = ?,
T1.天気状況 = ?,
T1.天気ﾏｰｸ = ?,
T1.担当ｺｰﾄﾞ = ?,
T1.担当 = ?,
T1.1号機現金枚数 = ?,
T1.1号機現金金額 = ?,
T1.1号機精算枚数 = ?,
T1.1号機精算金額 = ?,
T1.2号機現金枚数 = ?,
T1.2号機現金金額 = ?,
T1.2号機精算枚数 = ?,
T1.2号機精算金額 = ?,
T1.3号機現金枚数 = ?,
T1.3号機現金金額 = ?,
T1.3号機精算枚数 = ?,
T1.3号機精算金額 = ?,
T1.4号機現金枚数 = ?,
T1.4号機現金金額 = ?,
T1.4号機精算枚数 = ?,
T1.4号機精算金額 = ?,
T1.5号機現金枚数 = ?,
T1.5号機現金金額 = ?,
T1.5号機精算枚数 = ?,
T1.5号機精算金額 = ?,
T1.1号機未精算枚数 = ?,
T1.1号機未精算金額 = ?,
T1.2号機未精算枚数 = ?,
T1.2号機未精算金額 = ?,
T1.3号機未精算枚数 = ?,
T1.3号機未精算金額 = ?,
T1.4号機未精算枚数 = ?,
T1.4号機未精算金額 = ?,
T1.5号機未精算枚数 = ?,
T1.5号機未精算金額 = ?,
T1.1号機QR件数 = ?,
T1.1号機QR金額 = ?,
T1.2号機QR件数 = ?,
T1.2号機QR金額 = ?,
T1.3号機QR件数 = ?,
T1.3号機QR金額 = ?,
T1.4号機QR件数 = ?,
T1.4号機QR金額 = ?,
T1.5号機QR件数 = ?,
T1.5号機QR金額 = ?,
T1.1号機QR精算件数 = ?,
T1.1号機QR精算金額 = ?,
T1.2号機QR精算件数 = ?,
T1.2号機QR精算金額 = ?,
T1.3号機QR精算件数 = ?,
T1.3号機QR精算金額 = ?,
T1.4号機QR精算件数 = ?,
T1.4号機QR精算金額 = ?,
T1.5号機QR精算件数 = ?,
T1.5号機QR精算金額 = ?,
T1.1号機電子マネ件数 = ?,
T1.1号機電子マネ金額 = ?,
T1.2号機電子マネ件数 = ?,
T1.2号機電子マネ金額 = ?,
T1.3号機電子マネ件数 = ?,
T1.3号機電子マネ金額 = ?,
T1.4号機電子マネ件数 = ?,
T1.4号機電子マネ金額 = ?,
T1.5号機電子マネ件数 = ?,
T1.5号機電子マネ金額 = ?,
T1.1号機電子マネ精算件数 = ?,
T1.1号機電子マネ精算金額 = ?,
T1.2号機電子マネ精算件数 = ?,
T1.2号機電子マネ精算金額 = ?,
T1.3号機電子マネ精算件数 = ?,
T1.3号機電子マネ精算金額 = ?,
T1.4号機電子マネ精算件数 = ?,
T1.4号機電子マネ精算金額 = ?,
T1.5号機電子マネ精算件数 = ?,
T1.5号機電子マネ精算金額 = ?,
T1.1号機クレジット件数 = ?,
T1.1号機クレジット金額 = ?,
T1.2号機クレジット件数 = ?,
T1.2号機クレジット金額 = ?,
T1.3号機クレジット件数 = ?,
T1.3号機クレジット金額 = ?,
T1.4号機クレジット件数 = ?,
T1.4号機クレジット金額 = ?,
T1.5号機クレジット件数 = ?,
T1.5号機クレジット金額 = ?,
T1.1号機クレジット精算件数 = ?,
T1.1号機クレジット精算金額 = ?,
T1.2号機クレジット精算件数 = ?,
T1.2号機クレジット精算金額 = ?,
T1.3号機クレジット精算件数 = ?,
T1.3号機クレジット精算金額 = ?,
T1.4号機クレジット精算件数 = ?,
T1.4号機クレジット精算金額 = ?,
T1.5号機クレジット精算件数 = ?,
T1.5号機クレジット精算金額 = ?,
T1.大人入浴券枚数 = ?,
T1.大人入浴セット券枚数 = ?,
T1.小人入浴券枚数 = ?,
T1.回数券回収 = ?,
T1.招待券回収 = ?,
T1.優待券回収 = ?,
T1.感謝祭招待券回収 = ?,
T1.ﾎﾟｲﾝﾄｶｰﾄﾞ大人回収 = ?,
T1.ﾎﾟｲﾝﾄｶｰﾄﾞﾞ小人回収 = ?,
T1.回数券売数 = ?,
T1.過去回数券回収 = ?,
T1.販売NO（始まり） = ?,
T1.販売NO（終わり） = ?,
T1.釣銭（ﾌﾛﾝﾄ含む） = ?,
T1.電話料投入 = ?,
T1.手売（金額） = ?,
T1.優待券販売（枚数） = ?,
T1.優待券販売（金額） = ?,
T1.本日未投入金額（未確定） = ?,
T1.本日未投入金額（確定） = ?,
T1.過不足 = ?,
T1.前日未投入金額 = ?,
T1.投入ﾚｼｰﾄ合計金額 = ?,
T1.備考 = ?,
T1.ｴｽｶｯﾄ男性 = ?,
T1.ｴｽｶｯﾄ女性 = ?,
T1.ｴｽｶｯﾄ子供 = ?,
T1.6回数券回収 = ?,
T1.6回数券売数 = ?,
T1.6販売NO（始まり） = ?,
T1.6販売NO（終わり） = ?,
T1.男回数券枚数 = ?,
T1.女回数券枚数 = ?,
T1.6男回数券枚数 = ?,
T1.6女回数券枚数 = ?,
T1.ｸｰﾎﾟﾝ回収 = ?,
T1.リアレジ金額 = ?,
T1.リアレジ金額回数券系 = ?,
T1.リアレジ金額リラク系 = ?,
T1.報告ｽﾍﾟｰｽ = ?
            WHERE id = ?
        `
		_, err = db.Exec(updateQuery, input.ID,
			parsedDate,
			input.WeatherCode,
			input.WeatherCondition,
			input.WeatherMark,
			input.StaffCode,
			input.StaffName,
			input.Machine1CashCount,
			input.Machine1CashAmount,
			input.Machine1SettleCount,
			input.Machine1SettleAmount,
			input.Machine2CashCount,
			input.Machine2CashAmount,
			input.Machine2SettleCount,
			input.Machine2SettleAmount,
			input.Machine3CashCount,
			input.Machine3CashAmount,
			input.Machine3SettleCount,
			input.Machine3SettleAmount,
			input.Machine4CashCount,
			input.Machine4CashAmount,
			input.Machine4SettleCount,
			input.Machine4SettleAmount,
			input.Machine5CashCount,
			input.Machine5CashAmount,
			input.Machine5SettleCount,
			input.Machine5SettleAmount,
			input.Machine1UnsettledCount,
			input.Machine1UnsettledAmount,
			input.Machine2UnsettledCount,
			input.Machine2UnsettledAmount,
			input.Machine3UnsettledCount,
			input.Machine3UnsettledAmount,
			input.Machine4UnsettledCount,
			input.Machine4UnsettledAmount,
			input.Machine5UnsettledCount,
			input.Machine5UnsettledAmount,
			input.Machine1QrCount,
			input.Machine1QrAmount,
			input.Machine2QrCount,
			input.Machine2QrAmount,
			input.Machine3QrCount,
			input.Machine3QrAmount,
			input.Machine4QrCount,
			input.Machine4QrAmount,
			input.Machine5QrCount,
			input.Machine5QrAmount,
			input.Machine1QrSettleCount,
			input.Machine1QrSettleAmount,
			input.Machine2QrSettleCount,
			input.Machine2QrSettleAmount,
			input.Machine3QrSettleCount,
			input.Machine3QrSettleAmount,
			input.Machine4QrSettleCount,
			input.Machine4QrSettleAmount,
			input.Machine5QrSettleCount,
			input.Machine5QrSettleAmount,
			input.Machine1ECount,
			input.Machine1EAmount,
			input.Machine2ECount,
			input.Machine2EAmount,
			input.Machine3ECount,
			input.Machine3EAmount,
			input.Machine4ECount,
			input.Machine4EAmount,
			input.Machine5ECount,
			input.Machine5EAmount,
			input.Machine1ESettleCount,
			input.Machine1ESettleAmount,
			input.Machine2ESettleCount,
			input.Machine2ESettleAmount,
			input.Machine3ESettleCount,
			input.Machine3ESettleAmount,
			input.Machine4ESettleCount,
			input.Machine4ESettleAmount,
			input.Machine5ESettleCount,
			input.Machine5ESettleAmount,
			input.Machine1CCount,
			input.Machine1CAmount,
			input.Machine2CCount,
			input.Machine2CAmount,
			input.Machine3CCount,
			input.Machine3CAmount,
			input.Machine4CCount,
			input.Machine4CAmount,
			input.Machine5CCount,
			input.Machine5CAmount,
			input.Machine1CSettleCount,
			input.Machine1CSettleAmount,
			input.Machine2CSettleCount,
			input.Machine2CSettleAmount,
			input.Machine3CSettleCount,
			input.Machine3CSettleAmount,
			input.Machine4CSettleCount,
			input.Machine4CSettleAmount,
			input.Machine5CSettleCount,
			input.Machine5CSettleAmount,
			input.AdultTicketCount,
			input.AdultSetTicketCount,
			input.ChildTicketCount,
			input.TicketCount,
			input.InvitationTicketCount,
			input.YuutaikenTicketCount,
			input.InfantTicketCount,
			input.PointCardAdultCount,
			input.PointCardChildCount,
			input.TicketSalesCount,
			input.OldTicketCount,
			input.SalesNoStart,
			input.SalesNoEnd,
			input.Change,
			input.PhoneFee,
			input.Teuri,
			input.YuutaikenSalesCount,
			input.YuutaikenSalesAmount,
			input.HonjitsuMitounyuuAmountUncertain,
			input.HonjitsuMitounyuuAmountCertain,
			input.Deficiency,
			input.ZenjitsuMitounyuuAmount,
			input.ReceiptTotalAmount,
			input.Remarks,
			input.SCutMale,
			input.SCutFemale,
			input.SCutChild,
			input.SixTicketCount,
			input.SixTicketSalesCount,
			input.SixSalesNoStart,
			input.SixSalesNoEnd,
			input.MaleTicketCount,
			input.FemaleTicketCount,
			input.SixMaleTicketCount,
			input.SixFemaleTicketCount,
			input.CouponCount,
			input.RearegiAmount,
			input.RearegiTicketAmount,
			input.RearegiRelaxAmount,
			input.ReportSpace, input.ID)
		if err != nil {
			return nil, true, "更新", fmt.Errorf("error updating record: %v", err)
		}
		return input, true, "更新", nil
	}

	// Record does not exist, perform an insert
	insertQuery := `
        INSERT INTO 日次報告ﾃｰﾌﾞﾙ (ID,
日付,
天気ｺｰﾄﾞ,
天気状況,
天気ﾏｰｸ,
担当ｺｰﾄﾞ,
担当,
1号機現金枚数,
1号機現金金額,
1号機精算枚数,
1号機精算金額,
2号機現金枚数,
2号機現金金額,
2号機精算枚数,
2号機精算金額,
3号機現金枚数,
3号機現金金額,
3号機精算枚数,
3号機精算金額,
4号機現金枚数,
4号機現金金額,
4号機精算枚数,
4号機精算金額,
5号機現金枚数,
5号機現金金額,
5号機精算枚数,
5号機精算金額,
1号機未精算枚数,
1号機未精算金額,
2号機未精算枚数,
2号機未精算金額,
3号機未精算枚数,
3号機未精算金額,
4号機未精算枚数,
4号機未精算金額,
5号機未精算枚数,
5号機未精算金額,
1号機QR件数,
1号機QR金額,
2号機QR件数,
2号機QR金額,
3号機QR件数,
3号機QR金額,
4号機QR件数,
4号機QR金額,
5号機QR件数,
5号機QR金額,
1号機QR精算件数,
1号機QR精算金額,
2号機QR精算件数,
2号機QR精算金額,
3号機QR精算件数,
3号機QR精算金額,
4号機QR精算件数,
4号機QR精算金額,
5号機QR精算件数,
5号機QR精算金額,
1号機電子マネ件数,
1号機電子マネ金額,
2号機電子マネ件数,
2号機電子マネ金額,
3号機電子マネ件数,
3号機電子マネ金額,
4号機電子マネ件数,
4号機電子マネ金額,
5号機電子マネ件数,
5号機電子マネ金額,
1号機電子マネ精算件数,
1号機電子マネ精算金額,
2号機電子マネ精算件数,
2号機電子マネ精算金額,
3号機電子マネ精算件数,
3号機電子マネ精算金額,
4号機電子マネ精算件数,
4号機電子マネ精算金額,
5号機電子マネ精算件数,
5号機電子マネ精算金額,
1号機クレジット件数,
1号機クレジット金額,
2号機クレジット件数,
2号機クレジット金額,
3号機クレジット件数,
3号機クレジット金額,
4号機クレジット件数,
4号機クレジット金額,
5号機クレジット件数,
5号機クレジット金額,
1号機クレジット精算件数,
1号機クレジット精算金額,
2号機クレジット精算件数,
2号機クレジット精算金額,
3号機クレジット精算件数,
3号機クレジット精算金額,
4号機クレジット精算件数,
4号機クレジット精算金額,
5号機クレジット精算件数,
5号機クレジット精算金額,
大人入浴券枚数,
大人入浴セット券枚数,
小人入浴券枚数,
回数券回収,
招待券回収,
優待券回収,
感謝祭招待券回収,
ﾎﾟｲﾝﾄｶｰﾄﾞ大人回収,
ﾎﾟｲﾝﾄｶｰﾄﾞﾞ小人回収,
回数券売数,
過去回数券回収,
販売NO（始まり）,
販売NO（終わり）,
釣銭（ﾌﾛﾝﾄ含む）,
電話料投入,
手売（金額）,
優待券販売（枚数）,
優待券販売（金額）,
本日未投入金額（未確定）,
本日未投入金額（確定）,
過不足,
前日未投入金額,
投入ﾚｼｰﾄ合計金額,
備考,
ｴｽｶｯﾄ男性,
ｴｽｶｯﾄ女性,
ｴｽｶｯﾄ子供,
6回数券回収,
6回数券売数,
6販売NO（始まり）,
6販売NO（終わり）,
男回数券枚数,
女回数券枚数,
6男回数券枚数,
6女回数券枚数,
ｸｰﾎﾟﾝ回収,
リアレジ金額,
リアレジ金額回数券系,
リアレジ金額リラク系,
報告ｽﾍﾟｰｽ)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `
	_, err = db.Exec(insertQuery, input.ID,
		parsedDate,
		input.WeatherCode,
		input.WeatherCondition,
		input.WeatherMark,
		input.StaffCode,
		input.StaffName,
		input.Machine1CashCount,
		input.Machine1CashAmount,
		input.Machine1SettleCount,
		input.Machine1SettleAmount,
		input.Machine2CashCount,
		input.Machine2CashAmount,
		input.Machine2SettleCount,
		input.Machine2SettleAmount,
		input.Machine3CashCount,
		input.Machine3CashAmount,
		input.Machine3SettleCount,
		input.Machine3SettleAmount,
		input.Machine4CashCount,
		input.Machine4CashAmount,
		input.Machine4SettleCount,
		input.Machine4SettleAmount,
		input.Machine5CashCount,
		input.Machine5CashAmount,
		input.Machine5SettleCount,
		input.Machine5SettleAmount,
		input.Machine1UnsettledCount,
		input.Machine1UnsettledAmount,
		input.Machine2UnsettledCount,
		input.Machine2UnsettledAmount,
		input.Machine3UnsettledCount,
		input.Machine3UnsettledAmount,
		input.Machine4UnsettledCount,
		input.Machine4UnsettledAmount,
		input.Machine5UnsettledCount,
		input.Machine5UnsettledAmount,
		input.Machine1QrCount,
		input.Machine1QrAmount,
		input.Machine2QrCount,
		input.Machine2QrAmount,
		input.Machine3QrCount,
		input.Machine3QrAmount,
		input.Machine4QrCount,
		input.Machine4QrAmount,
		input.Machine5QrCount,
		input.Machine5QrAmount,
		input.Machine1QrSettleCount,
		input.Machine1QrSettleAmount,
		input.Machine2QrSettleCount,
		input.Machine2QrSettleAmount,
		input.Machine3QrSettleCount,
		input.Machine3QrSettleAmount,
		input.Machine4QrSettleCount,
		input.Machine4QrSettleAmount,
		input.Machine5QrSettleCount,
		input.Machine5QrSettleAmount,
		input.Machine1ECount,
		input.Machine1EAmount,
		input.Machine2ECount,
		input.Machine2EAmount,
		input.Machine3ECount,
		input.Machine3EAmount,
		input.Machine4ECount,
		input.Machine4EAmount,
		input.Machine5ECount,
		input.Machine5EAmount,
		input.Machine1ESettleCount,
		input.Machine1ESettleAmount,
		input.Machine2ESettleCount,
		input.Machine2ESettleAmount,
		input.Machine3ESettleCount,
		input.Machine3ESettleAmount,
		input.Machine4ESettleCount,
		input.Machine4ESettleAmount,
		input.Machine5ESettleCount,
		input.Machine5ESettleAmount,
		input.Machine1CCount,
		input.Machine1CAmount,
		input.Machine2CCount,
		input.Machine2CAmount,
		input.Machine3CCount,
		input.Machine3CAmount,
		input.Machine4CCount,
		input.Machine4CAmount,
		input.Machine5CCount,
		input.Machine5CAmount,
		input.Machine1CSettleCount,
		input.Machine1CSettleAmount,
		input.Machine2CSettleCount,
		input.Machine2CSettleAmount,
		input.Machine3CSettleCount,
		input.Machine3CSettleAmount,
		input.Machine4CSettleCount,
		input.Machine4CSettleAmount,
		input.Machine5CSettleCount,
		input.Machine5CSettleAmount,
		input.AdultTicketCount,
		input.AdultSetTicketCount,
		input.ChildTicketCount,
		input.TicketCount,
		input.InvitationTicketCount,
		input.YuutaikenTicketCount,
		input.InfantTicketCount,
		input.PointCardAdultCount,
		input.PointCardChildCount,
		input.TicketSalesCount,
		input.OldTicketCount,
		input.SalesNoStart,
		input.SalesNoEnd,
		input.Change,
		input.PhoneFee,
		input.Teuri,
		input.YuutaikenSalesCount,
		input.YuutaikenSalesAmount,
		input.HonjitsuMitounyuuAmountUncertain,
		input.HonjitsuMitounyuuAmountCertain,
		input.Deficiency,
		input.ZenjitsuMitounyuuAmount,
		input.ReceiptTotalAmount,
		input.Remarks,
		input.SCutMale,
		input.SCutFemale,
		input.SCutChild,
		input.SixTicketCount,
		input.SixTicketSalesCount,
		input.SixSalesNoStart,
		input.SixSalesNoEnd,
		input.MaleTicketCount,
		input.FemaleTicketCount,
		input.SixMaleTicketCount,
		input.SixFemaleTicketCount,
		input.CouponCount,
		input.RearegiAmount,
		input.RearegiTicketAmount,
		input.RearegiRelaxAmount,
		input.ReportSpace)
	if err != nil {
		return nil, false, "登録", fmt.Errorf("error inserting record: %v", err)
	}

	return input, false, "登録", nil
}
